FROM tomcat
LABEL maintainer="xmigrate.cloud"
{% for artefact in artefacts.APP_DIR %}
COPY {{ artefact }} /usr/local/tomcat/webapps
{% endfor %}
COPY {{ artefacts.APP_CONFIG }} /usr/local/tomcat/conf/tomcat-users.xml
EXPOSE {{ artefacts.APP_PORT }}
CMD ["catalina.sh", "run"]