FROM registry.access.redhat.com/jboss-eap-7/eap71-openshift
LABEL maintainer="xmigrate.cloud"
{% for artefact in artefacts.APP_DIR %}
COPY {{ artefact }} standalone/deployments
{% endfor %}
COPY {{ artefacts.APP_CONFIG }} /bin/standalone/configuration/standalone.xml
EXPOSE {{ artefacts.APP_PORT }}
CMD ["standalone.sh", "run"]